env:
  global:
    - NODE_ENV=test
language: node_js

node_js:
 - "stable"
install:
  - npm install
services:
  - postgresql

before_script:
  - psql -c 'create database testDB;' -U postgres
script: 
  - npm test
